### ISSUE TITLE
built-in usage hints for "run" command need formatting

### ISSUE THREAD

**Issue by qrkourier** [hashicorp/tfc-workflows-tooling#13]
Issues I encountered:

1. Running `tfci run` should list available sub-commands of `run`, but only `apply` is listed in the first section of the output. 
2. The global options are printed redundantly for each sub-command
3. Each sub-command's usage hint is obscured by the formatting. The hint is indented, but the redundant global options and sub-command options text are not indented, which hides the usage hint for each sub-command. A divider or heading or indentation-implied hierarchy would be helpful to distinguish where a sub-command's usage hint begins and ends.

Reproduce the output with this command:

```bash
docker run -it --rm \
  -e "TF_API_TOKEN" \
  -e "TF_CLOUD_ORGANIZATION" \
  hashicorp/tfci:v1.0.0 \
  tfci run
```

**Comment by ggambetti** [comment]
This appears to be an issue with the usage of the underlying `mitchellh/cli` library. It appears the implementation of `Command.Synopsis()` is incorrect across all implemented commands.

[Command.Synopsis()](https://github.com/mitchellh/cli/blob/v1.1.5/command.go#L28-L30) is used for help formatting.
