### ISSUE TITLE
create run `payload` is empty in v1.0.3

### ISSUE THREAD

**Issue by jmosawy** [hashicorp/tfc-workflows-tooling#45]
Hi,

I'd like to report an issue I started having with the create-run in v1.0.3 (it wasn't there in v1.0.2), so I hope we can get it fixed. I assume the following change in v1.0.3 is causing the issue (unfortunately, I'm not familiar with Go, so I can't really tell)

https://github.com/hashicorp/tfc-workflows-tooling/compare/v1.0.2...v1.0.3#diff-081ffb9fc91bc673b661fe6e89423940f04d5b809bc666a0a4f8eb1f7d7d39e7R104-R108

Here's some more detail:

- I have created a GitHub Actions workflow identical to this: https://github.com/hashicorp/tfc-workflows-github/blob/main/workflow-templates/terraform-cloud.apply-run.workflow.yml
- the issue is in the last step where I need to use `apply-run`, the `payload` property in https://github.com/hashicorp/tfc-workflows-github/blob/b5ae00d6ff4f940fc11ec6e70346e9c693590b5e/workflow-templates/terraform-cloud.apply-run.workflow.yml#L58C26-L58C58 seems to be _empty_, and that's why `fromJson` is throwing an error.

**Comment by mjyocca** [comment]
@jmosawy Thank you for bringing this to our attention. We will ship out a fix.

**Comment by mjyocca** [comment]
@jmosawy v1.0.4 is now available with the fix for the reported issue.
