### ISSUE TITLE
create-run can exit too early with auto-apply enabled

### ISSUE THREAD

**Issue by brosner** [hashicorp/tfc-workflows-tooling#49]
I am seeing a case where the `create-run` command (I use it as a GHA action) will bail out early with auto-apply enabled. This isn't consistent because the loop that does run completion checking can be sleeping when the run transitions from `planning` -> `planned` -> `apply_queued` -> etc...

See https://github.com/hashicorp/tfc-workflows-tooling/blob/main/internal/cloud/run.go#L172

I am not sure what the best fix is here, but here are the options I see:

1. Turn off auto-apply and rely on auto applying in the caller (in my case using GHA)
2. Remove `planned` as a a desired status if auto-apply is enabled
3. Allow the desired status to be passed in
4. Something else I didn't think of

**Comment by mjyocca** [comment]
Thanks @brosner for submitting an issue for this bug. Will patch out a fix.
