### ISSUE TITLE
Add support for terraform workspace outputs.

### ISSUE THREAD

**Issue by srlynch1** [hashicorp/tfc-workflows-tooling#9]
As a consumer of these actions, I need to easily fetch the workspace terraform outputs after an apply run.

As an example, I need to pass a tf output to subsequent action in my pipeline. 

Terraform outputs are in Go-tfe https://github.com/hashicorp/go-tfe/blob/main/state_version_output.go#L22

**Comment by ikunduraci** [comment]
💯
